workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: app.durian7111.apple315
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Generate iOS project
        script: |
          flutter create --org app.durian7111 --project-name apple315 .
      - name: Get Flutter packages
        script: flutter pub get
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Build iOS IPA
        script: |
          flutter build ipa --release --no-codesign
          xcode-project build-ipa --workspace ios/Runner.xcworkspace --scheme Runner
    artifacts:
      - build/ios/ipa/*.ipa
      - '**/*.ipa'
    publishing:
      email:
        recipients:
          - 3371574658@qq.com
        notify:
          success: true
          failure: true
